export type Metadata = { offset?: number; collectedIds?: string[] };

export const Genres = [
    { id: "artbook", value: "Artbook" },
    { id: "cartoon", value: "Cartoon" },
    { id: "comic", value: "Comic" },
    { id: "doujinshi", value: "Doujinshi" },
    { id: "imageset", value: "Imageset" },
    { id: "manga", value: "Manga" },
    { id: "manhua", value: "Manhua" },
    { id: "manhwa", value: "Manhwa" },
    { id: "webtoon", value: "Webtoon" },
    { id: "western", value: "Western" },
    { id: "_4_koma", value: "4-Koma" },
    { id: "oneshot", value: "Oneshot" },
    { id: "shoujo", value: "Shoujo(G)" },
    { id: "shounen", value: "Shounen(B)" },
    { id: "josei", value: "Josei(W)" },
    { id: "seinen", value: "Seinen(M)" },
    { id: "yuri", value: "Yuri(GL)" },
    { id: "yaoi", value: "Yaoi(BL)" },
    { id: "bara", value: "Bara(ML)" },
    { id: "kodomo", value: "Kodomo(Kid)" },
    { id: "old_people", value: "Silver & Golden" },
    { id: "non_human", value: "Non-human" },
    { id: "gore", value: "Gore" },
    { id: "bloody", value: "Bloody" },
    { id: "violence", value: "Violence" },
    { id: "ecchi", value: "Ecchi" },
    { id: "adult", value: "Adult" },
    { id: "mature", value: "Mature" },
    { id: "smut", value: "Smut" },
    { id: "hentai", value: "Hentai" },
    { id: "action", value: "Action" },
    { id: "adaptation", value: "Adaptation" },
    { id: "adventure", value: "Adventure" },
    { id: "age_gap", value: "Age Gap" },
    { id: "aliens", value: "Aliens" },
    { id: "animals", value: "Animals" },
    { id: "anthology", value: "Anthology" },
    { id: "beasts", value: "Beasts" },
    { id: "bodyswap", value: "Bodyswap" },
    { id: "boys", value: "Boys" },
    { id: "cars", value: "Cars" },
    { id: "cheating_infidelity", value: "Cheating/Infidelity" },
    { id: "childhood_friends", value: "Childhood Friends" },
    { id: "college_life", value: "College life" },
    { id: "comedy", value: "Comedy" },
    { id: "contest_winning", value: "Contest winning" },
    { id: "cooking", value: "Cooking" },
    { id: "crime", value: "Crime" },
    { id: "crossdressing", value: "Crossdressing" },
    { id: "dementia", value: "Dementia" },
    { id: "delinquents", value: "Delinquents" },
    { id: "demons", value: "Demons" },
    { id: "drama", value: "Drama" },
    { id: "dungeons", value: "Dungeons" },
    { id: "emperor_daughte", value: "Emperor's daughter" },
    { id: "fan_colored", value: "Fan-Colored" },
    { id: "fantasy", value: "Fantasy" },
    { id: "fetish", value: "Fetish" },
    { id: "full_color", value: "Full Color" },
    { id: "game", value: "Game" },
    { id: "gender_bender", value: "Gender Bender" },
    { id: "genderswap", value: "Genderswap" },
    { id: "ghosts", value: "Ghosts" },
    { id: "girls", value: "Girls" },
    { id: "gyaru", value: "Gyaru" },
    { id: "harlequin", value: "Harlequin" },
    { id: "harem", value: "Harem" },
    { id: "historical", value: "Historical" },
    { id: "horror", value: "Horror" },
    { id: "incest", value: "Incest" },
    { id: "isekai", value: "Isekai" },
    { id: "kids", value: "Kids" },
    { id: "magical_girls", value: "Magical Girls" },
    { id: "magic", value: "Magic" },
    { id: "martial_arts", value: "Martial Arts" },
    { id: "mecha", value: "Mecha" },
    { id: "medical", value: "Medical" },
    { id: "military", value: "Military" },
    { id: "monster_girls", value: "Monster Girls" },
    { id: "monsters", value: "Monsters" },
    { id: "music", value: "Music" },
    { id: "mystery", value: "Mystery" },
    { id: "netorare", value: "Netorare/NTR" },
    { id: "ninja", value: "Ninja" },
    { id: "office_workers", value: "Office Workers" },
    { id: "omegaverse", value: "Omegaverse" },
    { id: "parody", value: "Parody" },
    { id: "philosophical", value: "Philosophical" },
    { id: "police", value: "Police" },
    { id: "post_apocalyptic", value: "Post-Apocalyptic" },
    { id: "psychological", value: "Psychological" },
    { id: "regression", value: "Regression" },
    { id: "reincarnation", value: "Reincarnation" },
    { id: "revenge", value: "Revenge" },
    { id: "reverse_harem", value: "Reverse Harem" },
    { id: "reverse_isekai", value: "Reverse Isekai" },
    { id: "romance", value: "Romance" },
    { id: "royal_family", value: "Royal family" },
    { id: "royalty", value: "Royalty" },
    { id: "samurai", value: "Samurai" },
    { id: "school_life", value: "School Life" },
    { id: "sci_fi", value: "Sci-Fi" },
    { id: "shoujo_ai", value: "Shoujo ai" },
    { id: "shounen_ai", value: "Shounen ai" },
    { id: "showbiz", value: "Showbiz" },
    { id: "slice_of_life", value: "Slice of Life" },
    { id: "sm_bdsm", value: "SM/BDSM/SUB-DOM" },
    { id: "space", value: "Space" },
    { id: "sports", value: "Sports" },
    { id: "super_power", value: "Super Power" },
    { id: "superhero", value: "Superhero" },
    { id: "supernatural", value: "Supernatural" },
    { id: "survival", value: "Survival" },
    { id: "thriller", value: "Thriller" },
    { id: "time_travel", value: "Time Travel" },
    { id: "tower_climbing", value: "Tower Climbing" },
    { id: "traditional_games", value: "Traditional Games" },
    { id: "tragedy", value: "Tragedy" },
    { id: "transmigration", value: "Transmigration" },
    { id: "vampires", value: "Vampires" },
    { id: "video_games", value: "Video Games" },
    { id: "villainess", value: "Villainess" },
    { id: "virtual_reality", value: "Virtual Reality" },
    { id: "wuxia", value: "Wuxia" },
    { id: "xianxia", value: "Xianxia" },
    { id: "xuanhuan", value: "Xuanhuan" },
    { id: "yakuzas", value: "Yakuzas" },
    { id: "zombies", value: "Zombies" },
];

export const MatureGenres = [
    "Adult",
    "Ecchi",
    "Erotica",
    "Sexual violence",
    "Gore",
    "Bloody",
    "Violence",
    "Smut",
    "Hentai",
    "Yuri(GL)",
    "Yaoi(BL)",
    "Bara(ML)",
    "Netorare/NTR",
    "Incest",
    "SM/BDSM/SUB-DOM",
];

export const AdultGenres = ["Erotica", "Sexual violence", "Hentai", "Smut"];

export const Languages = [
    { name: "English", value: "en" },
    { name: "Afrikaans", value: "af" },
    { name: "Albanian", value: "sq" },
    { name: "Amharic", value: "am" },
    { name: "Arabic", value: "ar" },
    { name: "Armenian", value: "hy" },
    { name: "Azerbaijani", value: "az" },
    { name: "Belarusian", value: "be" },
    { name: "Bengali", value: "bn" },
    { name: "Bosnian", value: "bs" },
    { name: "Bulgarian", value: "bg" },
    { name: "Burmese", value: "my" },
    { name: "Cambodian", value: "km" },
    { name: "Catalan", value: "ca" },
    { name: "Cebuano", value: "ceb" },
    { name: "Chinese", value: "zh" },
    { name: "Chinese (繁)", value: "zh_tw" },
    { name: "Chinese (粵)", value: "zh_hk" },
    { name: "Croatian", value: "hr" },
    { name: "Czech", value: "cs" },
    { name: "Danish", value: "da" },
    { name: "Dutch", value: "nl" },
    { name: "Estonian", value: "et" },
    { name: "Faroese", value: "fo" },
    { name: "Filipino", value: "fil" },
    { name: "Finnish", value: "fi" },
    { name: "French", value: "fr" },
    { name: "Georgian", value: "ka" },
    { name: "German", value: "de" },
    { name: "Greek", value: "el" },
    { name: "Guarani", value: "gn" },
    { name: "Gujarati", value: "gu" },
    { name: "Haitian Creole", value: "ht" },
    { name: "Hausa", value: "ha" },
    { name: "Hebrew", value: "he" },
    { name: "Hindi", value: "hi" },
    { name: "Hungarian", value: "hu" },
    { name: "Icelandic", value: "is" },
    { name: "Igbo", value: "ig" },
    { name: "Indonesian", value: "id" },
    { name: "Irish", value: "ga" },
    { name: "Italian", value: "it" },
    { name: "Japanese", value: "ja" },
    { name: "Javanese", value: "jv" },
    { name: "Kannada", value: "kn" },
    { name: "Kazakh", value: "kk" },
    { name: "Korean", value: "ko" },
    { name: "Kurdish", value: "ku" },
    { name: "Kyrgyz", value: "ky" },
    { name: "Laothian", value: "lo" },
    { name: "Latvian", value: "lv" },
    { name: "Lithuanian", value: "lt" },
    { name: "Luxembourgish", value: "lb" },
    { name: "Macedonian", value: "mk" },
    { name: "Malagasy", value: "mg" },
    { name: "Malay", value: "ms" },
    { name: "Malayalam", value: "ml" },
    { name: "Maltese", value: "mt" },
    { name: "Maori", value: "mi" },
    { name: "Marathi", value: "mr" },
    { name: "Moldavian", value: "mo" },
    { name: "Mongolian", value: "mn" },
    { name: "Nepali", value: "ne" },
    { name: "Norwegian", value: "no" },
    { name: "Nyanja", value: "ny" },
    { name: "Pashto", value: "ps" },
    { name: "Persian", value: "fa" },
    { name: "Polish", value: "pl" },
    { name: "Portuguese", value: "pt" },
    { name: "Portuguese (BR)", value: "pt_br" },
    { name: "Romanian", value: "ro" },
    { name: "Romansh", value: "rm" },
    { name: "Russian", value: "ru" },
    { name: "Samoan", value: "sm" },
    { name: "Serbian", value: "sr" },
    { name: "Serbo-Croatian", value: "sh" },
    { name: "Sesotho", value: "st" },
    { name: "Shona", value: "sn" },
    { name: "Sindhi", value: "sd" },
    { name: "Sinhalese", value: "si" },
    { name: "Slovak", value: "sk" },
    { name: "Slovenian", value: "sl" },
    { name: "Somali", value: "so" },
    { name: "Spanish", value: "es" },
    { name: "Spanish (LA)", value: "es_419" },
    { name: "Swahili", value: "sw" },
    { name: "Swedish", value: "sv" },
    { name: "Tajik", value: "tg" },
    { name: "Tamil", value: "ta" },
    { name: "Telugu", value: "te" },
    { name: "Thai", value: "th" },
    { name: "Tigrinya", value: "ti" },
    { name: "Tonga", value: "to" },
    { name: "Turkish", value: "tr" },
    { name: "Turkmen", value: "tk" },
    { name: "Ukrainian", value: "uk" },
    { name: "Urdu", value: "ur" },
    { name: "Uzbek", value: "uz" },
    { name: "Vietnamese", value: "vi" },
    { name: "Yoruba", value: "yo" },
    { name: "Zulu", value: "zu" },
    { name: "Other", value: "_t" },
];
