// genreOptions.ts

export const genreOptions = [
  { id: "1", value: "4 koma" },
  { id: "2", value: "Action" },
  { id: "3", value: "Adult" },
  { id: "4", value: "Adventure" },
  { id: "5", value: "Artbook" },
  { id: "6", value: "Award winning" },
  { id: "7", value: "Comedy" },
  { id: "8", value: "Cooking" },
  { id: "9", value: "Doujinshi" },
  { id: "10", value: "Drama" },
  { id: "11", value: "Ecchi" },
  { id: "12", value: "Erotica" },
  { id: "13", value: "Fantasy" },
  { id: "14", value: "Gender Bender" },
  { id: "15", value: "Gore" },
  { id: "16", value: "Harem" },
  { id: "17", value: "Historical" },
  { id: "18", value: "Horror" },
  { id: "19", value: "Isekai" },
  { id: "20", value: "Josei" },
  { id: "21", value: "Loli" },
  { id: "22", value: "Manhua" },
  { id: "23", value: "Manhwa" },
  { id: "24", value: "Martial Arts" },
  { id: "25", value: "Mecha" },
  { id: "26", value: "Medical" },
  { id: "27", value: "Music" },
  { id: "28", value: "Mystery" },
  { id: "29", value: "One shot" },
  { id: "30", value: "Overpowered MC" },
  { id: "31", value: "Psychological" },
  { id: "32", value: "Reincarnation" },
  { id: "33", value: "Romance" },
  { id: "34", value: "School Life" },
  { id: "35", value: "Sci-fi" },
  { id: "36", value: "Seinen" },
  { id: "37", value: "Sexual violence" },
  { id: "38", value: "Shota" },
  { id: "39", value: "Shoujo" },
  { id: "40", value: "Shoujo Ai" },
  { id: "41", value: "Shounen" },
  { id: "42", value: "Shounen Ai" },
  { id: "43", value: "Slice of Life" },
  { id: "44", value: "Sports" },
  { id: "45", value: "Super power" },
  { id: "46", value: "Supernatural" },
  { id: "47", value: "Survival" },
  { id: "48", value: "Time Travel" },
  { id: "49", value: "Tragedy" },
  { id: "50", value: "Webtoon" },
  { id: "51", value: "Yaoi" },
  { id: "52", value: "Yuri" },
];
