// genres.ts

export const genres = [
  { id: "1", name: "4 koma" },
  { id: "2", name: "Action" },
  { id: "3", name: "Adult" },
  { id: "4", name: "Adventure" },
  { id: "5", name: "Artbook" },
  { id: "6", name: "Award winning" },
  { id: "7", name: "Comedy" },
  { id: "8", name: "Cooking" },
  { id: "9", name: "Doujinshi" },
  { id: "10", name: "Drama" },
  { id: "11", name: "Ecchi" },
  { id: "12", name: "Erotica" },
  { id: "13", name: "Fantasy" },
  { id: "14", name: "Gender Bender" },
  { id: "15", name: "Gore" },
  { id: "16", name: "Harem" },
  { id: "17", name: "Historical" },
  { id: "18", name: "Horror" },
  { id: "19", name: "Isekai" },
  { id: "20", name: "Josei" },
  { id: "21", name: "Loli" },
  { id: "22", name: "Manhua" },
  { id: "23", name: "Manhwa" },
  { id: "24", name: "Martial Arts" },
  { id: "25", name: "Mecha" },
  { id: "26", name: "Medical" },
  { id: "27", name: "Music" },
  { id: "28", name: "Mystery" },
  { id: "29", name: "One shot" },
  { id: "30", name: "Overpowered MC" },
  { id: "31", name: "Psychological" },
  { id: "32", name: "Reincarnation" },
  { id: "33", name: "Romance" },
  { id: "34", name: "School Life" },
  { id: "35", name: "Sci-fi" },
  { id: "36", name: "Seinen" },
  { id: "37", name: "Sexual violence" },
  { id: "38", name: "Shota" },
  { id: "39", name: "Shoujo" },
  { id: "40", name: "Shoujo Ai" },
  { id: "41", name: "Shounen" },
  { id: "42", name: "Shounen Ai" },
  { id: "43", name: "Slice of Life" },
  { id: "44", name: "Sports" },
  { id: "45", name: "Super power" },
  { id: "46", name: "Supernatural" },
  { id: "47", name: "Survival" },
  { id: "48", name: "Time Travel" },
  { id: "49", name: "Tragedy" },
  { id: "50", name: "Webtoon" },
  { id: "51", name: "Yaoi" },
  { id: "52", name: "Yuri" },
];
